# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=35)),
                ('account_type', models.IntegerField(max_length=1)),
                ('bank_code', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_city', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=35)),
                ('account_type', models.IntegerField(max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_transfer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_transfer.Beneficiary')),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_transfer.CustomerAccount')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_transfer.Customer'),
        ),
    ]
