# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='account_type',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='account_type',
            field=models.CharField(max_length=1),
        ),
    ]
