# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund_transfer', '0002_auto_20161116_0609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficiary',
            new_name='Payee',
        ),
        migrations.RenameField(
            model_name='fundtransfer',
            old_name='beneficiary',
            new_name='payee',
        ),
    ]
